# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2
jobs:
  build:
    docker:
      # specify the version
      - image: circleci/golang:1.9
      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      - image: postgres:9.6
        environment:
          POSTGRES_DB: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: password
    #### TEMPLATE_NOTE: go expects specific checkout path representing url
    #### expecting it in the form of
    ####   /go/src/github.com/circleci/go-tool
    ####   /go/src/bitbucket.org/circleci/go-tool
    working_directory: /go/src/github.com/grafeas/grafeas/
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: make prepare
      - run:
          name: Make protoc executables available globally
          command: |
                    echo 'export PATH=./bin:$PATH' >> $BASH_ENV
                    source /home/circleci/.bashrc
      - run: make build; make test
